In [1]:
import pandas as pd

In [70]:
df_refseq = pd.read_csv('../db_defense_systems/DefenseFinder/df-RefSeq.csv')

In [71]:
df_refseq

,sys_id,Assembly,replicon,type,subtype,sys_beg,sys_end,protein_in_syst,genes_count,name_of_profiles_in_sys,accession_in_sys,Superkingdom,phylum,class,order,family,genus,species
0,GCF_023612275_NZ_CP063766_Abi2_1,GCF_023612275.1,NZ_CP063766,Abi2,Abi2,GCF_023612275.1_NZ_CP063766_01013,GCF_023612275.1_NZ_CP063766_01013,GCF_023612275.1_NZ_CP063766_01013,1.0,Abi2__Abi_2,WP_010728290.1,Bacteria,Bacillota,Bacilli,Lactobacillales,Enterococcaceae,Enterococcus,Enterococcus lactis
1,GCF_900660665_NZ_LR215037_Abi2_1,GCF_900660665.1,NZ_LR215037,Abi2,Abi2,GCF_900660665.1_NZ_LR215037_00128,GCF_900660665.1_NZ_LR215037_00128,GCF_900660665.1_NZ_LR215037_00128,1.0,Abi2__Abi_2,WP_129646131.1,Bacteria,Mycoplasmatota,Mollicutes,Mycoplasmatales,Mycoplasmataceae,Mycoplasmopsis,Mycoplasmopsis maculosa
2,GCF_900660665_NZ_LR215037_Abi2_2,GCF_900660665.1,NZ_LR215037,Abi2,Abi2,GCF_900660665.1_NZ_LR215037_00677,GCF_900660665.1_NZ_LR215037_00677,GCF_900660665.1_NZ_LR215037_00677,1.0,Abi2__Abi_2,WP_129647121.1,Bacteria,Mycoplasmatota,Mollicutes,Mycoplasmatales,Mycoplasmataceae,Mycoplasmopsis,Mycoplasmopsis maculosa
3,GCF_008365255_NZ_CP043501_Abi2_1,GCF_008365255.1,NZ_CP043501,Abi2,Abi2,GCF_008365255.1_NZ_CP043501_01947,GCF_008365255.1_NZ_CP043501_01947,GCF_008365255.1_NZ_CP043501_01947,1.0,Abi2__Abi_2,WP_149208562.1,Bacteria,Bacillota,Bacilli,Bacillales,Bacillaceae,Bacillus,Bacillus paralicheniformis
4,GCF_009296125_NZ_CP017197_Abi2_1,GCF_009296125.1,NZ_CP017197,Abi2,Abi2,GCF_009296125.1_NZ_CP017197_01353,GCF_009296125.1_NZ_CP017197_01353,GCF_009296125.1_NZ_CP017197_01353,1.0,Abi2__Abi_2,WP_097001356.1,Bacteria,Bacillota,Bacilli,Lactobacillales,Lactobacillaceae,Leuconostoc,Leuconostoc gasicomitatum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172328,GCF_012029695_NZ_CP061390_Zorya_TypeI_1,GCF_012029695.2,NZ_CP061390,Zorya,Zorya_TypeI,GCF_012029695.2_NZ_CP061390_00118,GCF_012029695.2_NZ_CP061390_00121,"GCF_012029695_NZ_CP061390_00118,GCF_012029695_...",4.0,"Zorya__ZorA,Zorya__ZorB,Zorya_TypeI__ZorC,Zory...","WP_004182103.1,WP_004182101.1,WP_004182099.1,W...",Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Klebsiella,Klebsiella pneumoniae
172329,GCF_014396975_NZ_CP060719_Zorya_TypeI_1,GCF_014396975.1,NZ_CP060719,Zorya,Zorya_TypeI,GCF_014396975.1_NZ_CP060719_00618,GCF_014396975.1_NZ_CP060719_00621,"GCF_014396975_NZ_CP060719_00618,GCF_014396975_...",4.0,"Zorya_TypeI__ZorD,Zorya_TypeI__ZorC,Zorya__Zor...","WP_187553130.1,WP_187553131.1,WP_187553132.1,W...",Bacteria,Pseudomonadota,Gammaproteobacteria,Xanthomonadales,Xanthomonadaceae,Thermomonas,Thermomonas carbonis
172330,GCF_002055855_NZ_CP020067_Zorya_TypeI_1,GCF_002055855.1,NZ_CP020067,Zorya,Zorya_TypeI,GCF_002055855.1_NZ_CP020067_01216,GCF_002055855.1_NZ_CP020067_01219,"GCF_002055855_NZ_CP020067_01216,GCF_002055855_...",4.0,"Zorya_TypeI__ZorD,Zorya_TypeI__ZorC,Zorya__Zor...","WP_004178705.1,WP_004178703.1,WP_004195968.1,W...",Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Klebsiella,Klebsiella pneumoniae
172331,GCF_012029695_NZ_CP061389_Zorya_TypeI_1,GCF_012029695.2,NZ_CP061389,Zorya,Zorya_TypeI,GCF_012029695.2_NZ_CP061389_04302,GCF_012029695.2_NZ_CP061389_04305,"GCF_012029695_NZ_CP061389_04302,GCF_012029695_...",4.0,"Zorya_TypeI__ZorD,Zorya_TypeI__ZorC,Zorya__Zor...","WP_004178705.1,WP_004178703.1,WP_004195968.1,W...",Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Klebsiella,Klebsiella pneumoniae
172332,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1,NZ_AP018052,Zorya,Zorya_TypeI,GCF_002356355.1_NZ_AP018052_01338,GCF_002356355.1_NZ_AP018052_01341,"GCF_002356355_NZ_AP018052_01338,GCF_002356355_...",4.0,"Zorya__ZorA2,Zorya__ZorB,Zorya_TypeI__ZorC,Zor...","WP_096365918.1,WP_197703019.1,WP_157745444.1,W...",Bacteria,Pseudomonadota,Gammaproteobacteria,Chromatiales,NaN,Thiohalobacter,Thiohalobacter thiocyanaticus

In [ ]:
# Assuming your DataFrame is named df
# First, split each comma-separated string into lists
df_expanded = df.assign(
    name_of_profiles_in_sys=df['name_of_profiles_in_sys'].str.split(','),
    accession_in_sys=df['accession_in_sys'].str.split(','),
    protein_in_syst=df['protein_in_syst'].str.split(',')
)

# Then explode all three columns simultaneously to maintain alignment
df_expanded = df_expanded.explode(['name_of_profiles_in_sys', 'accession_in_sys', 'protein_in_syst'])

# Reset index if needed
df_expanded = df_expanded.reset_index(drop=True)

In [2]:
from Bio import Entrez
from Bio import SeqIO
import time
from tqdm import tqdm

In [ ]:
Entrez.email = "YOUR_EMAIL"  # Replace with your email
Entrez.api_key = "YOUR_API_KEY"  # Get from https://www.ncbi.nlm.nih.gov/account/

def fetch_protein_sequences_batch(accessions, batch_size=200, wait=0.1,max_retries=3):
    """Fetch multiple protein sequences in batches."""
    accession_to_sequence = {}
    
    for i in tqdm(range(0, len(accessions), batch_size)):
        batch = accessions[i:i + batch_size]
        
        for attempt in range(max_retries):
            try:
                handle = Entrez.efetch(
                    db="protein", 
                    id=",".join(batch),
                    rettype="fasta", 
                    retmode="text"
                )
                records = SeqIO.parse(handle, "fasta")
                
                for record in records:
                    acc = record.id.split("|")[3] if "|" in record.id else record.id
                    accession_to_sequence[acc] = str(record.seq)
                
                handle.close()
                break  # Success, exit retry loop
                
            except Exception as e:
                if attempt == max_retries - 1:
                    print(f"Failed batch after {max_retries} attempts: {e}")
                else:
                    time.sleep(1)  # Wait before retry
        
        time.sleep(wait)  # or 0.1 with API key
            
    return accession_to_sequence

In [ ]:
unique_accessions = df_expanded['accession_in_sys'].unique().tolist()
accession_to_sequence = fetch_protein_sequences_batch(unique_accessions)
df_expanded['protein_sequence'] = df_expanded['accession_in_sys'].map(accession_to_sequence)

In [ ]:
df_expanded.to_csv('df-sequences.csv')

In [ ]:

# Use it
unique_accessions = df_expanded['accession_in_sys'].unique().tolist()
accession_to_sequence = fetch_protein_sequences_batch(unique_accessions)
df_expanded['protein_sequence'] = df_expanded['accession_in_sys'].map(accession_to_sequence)

unique_accessions = df_expanded['accession_in_sys'].unique()
accession_to_sequence = {}

for accession in tqdm(unique_accessions, desc="Fetching protein sequences"):
    sequence = fetch_protein_sequence(accession)
    if sequence:
        accession_to_sequence[accession] = sequence
    time.sleep(0.34)

# Add sequences to the DataFrame
df_expanded['protein_sequence'] = df_expanded['accession_in_sys'].map(accession_to_sequence)

In [3]:
df_expanded = pd.read_csv('df-sequences.csv')

In [4]:
df_expanded[['sys_id', 'protein_sequence']]

,sys_id,protein_sequence
0,GCF_023612275_NZ_CP063766_Abi2_1,MKKYGSKQEYVKRPKSIINNRFPSKLKKKIRPNQYFYSRVRCQIIP...
1,GCF_900660665_NZ_LR215037_Abi2_1,MNKNNVKSLLSFEEQLNFLQSKYINWNNQEKFRFKIYLINYGYSHM...
2,GCF_900660665_NZ_LR215037_Abi2_2,MNKKIKTILTTDEQINLLEEWGLKWEDDYSRNILKIYLKNYGYKHI...
3,GCF_008365255_NZ_CP043501_Abi2_1,MVKGKTTNGLMRHLREKHGISINGSKHKKELLNMGYYHGYKGYRFI...
4,GCF_009296125_NZ_CP017197_Abi2_1,MTIYDTEQIKSFLGLRQIKSNDDFKAVETMSTDTAIKFKKYVEYLG...
...,...,...
380018,GCF_012029695_NZ_CP061389_Zorya_TypeI_1,MSWLNSFLVTLTSVEPHNVPFTVISIVSLAVACFLFFYLFRAIKIV...
380019,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,MSTKHLAELLDRLANAIVTLEGVALICILIALVALYNYLRFRARIA...
380020,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,MKRPAEHTTFEDDGAGYLISVSDMMAGLLFVFMITLMAFVINFQQA...
380021,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,MAGLKESLSSRVVTSPHSESWPAPALETAIREARWKLARVEPRDPP...
380022,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,MAELAWHVKDDGVEFQLQAEGKRVPLDQWGMHSIDLSSGQGTPGPL...

In [5]:
len(df_expanded['subtype'].unique())

265

## Clustering sequences

!mmseqs easy-cluster proteins_for_deeptmhmm.fasta clusters tmp \
  --min-seq-id 0.85 \
  -c 0.70

In [7]:
clusters = pd.read_csv(
    "./clustered_85/clusters_cluster.tsv",
    sep="\t",
    names=["rep_idx", "member_idx"]
)

In [ ]:
clusters = clusters.reset_index()

In [8]:
df_expanded

,Unnamed: 0,sys_id,Assembly,replicon,type,subtype,sys_beg,sys_end,protein_in_syst,genes_count,name_of_profiles_in_sys,accession_in_sys,Superkingdom,phylum,class,order,family,genus,species,protein_sequence
0,0,GCF_023612275_NZ_CP063766_Abi2_1,GCF_023612275.1,NZ_CP063766,Abi2,Abi2,GCF_023612275.1_NZ_CP063766_01013,GCF_023612275.1_NZ_CP063766_01013,GCF_023612275.1_NZ_CP063766_01013,1.0,Abi2__Abi_2,WP_010728290.1,Bacteria,Bacillota,Bacilli,Lactobacillales,Enterococcaceae,Enterococcus,Enterococcus lactis,MKKYGSKQEYVKRPKSIINNRFPSKLKKKIRPNQYFYSRVRCQIIP...
1,1,GCF_900660665_NZ_LR215037_Abi2_1,GCF_900660665.1,NZ_LR215037,Abi2,Abi2,GCF_900660665.1_NZ_LR215037_00128,GCF_900660665.1_NZ_LR215037_00128,GCF_900660665.1_NZ_LR215037_00128,1.0,Abi2__Abi_2,WP_129646131.1,Bacteria,Mycoplasmatota,Mollicutes,Mycoplasmatales,Mycoplasmataceae,Mycoplasmopsis,Mycoplasmopsis maculosa,MNKNNVKSLLSFEEQLNFLQSKYINWNNQEKFRFKIYLINYGYSHM...
2,2,GCF_900660665_NZ_LR215037_Abi2_2,GCF_900660665.1,NZ_LR215037,Abi2,Abi2,GCF_900660665.1_NZ_LR215037_00677,GCF_900660665.1_NZ_LR215037_00677,GCF_900660665.1_NZ_LR215037_00677,1.0,Abi2__Abi_2,WP_129647121.1,Bacteria,Mycoplasmatota,Mollicutes,Mycoplasmatales,Mycoplasmataceae,Mycoplasmopsis,Mycoplasmopsis maculosa,MNKKIKTILTTDEQINLLEEWGLKWEDDYSRNILKIYLKNYGYKHI...
3,3,GCF_008365255_NZ_CP043501_Abi2_1,GCF_008365255.1,NZ_CP043501,Abi2,Abi2,GCF_008365255.1_NZ_CP043501_01947,GCF_008365255.1_NZ_CP043501_01947,GCF_008365255.1_NZ_CP043501_01947,1.0,Abi2__Abi_2,WP_149208562.1,Bacteria,Bacillota,Bacilli,Bacillales,Bacillaceae,Bacillus,Bacillus paralicheniformis,MVKGKTTNGLMRHLREKHGISINGSKHKKELLNMGYYHGYKGYRFI...
4,4,GCF_009296125_NZ_CP017197_Abi2_1,GCF_009296125.1,NZ_CP017197,Abi2,Abi2,GCF_009296125.1_NZ_CP017197_01353,GCF_009296125.1_NZ_CP017197_01353,GCF_009296125.1_NZ_CP017197_01353,1.0,Abi2__Abi_2,WP_097001356.1,Bacteria,Bacillota,Bacilli,Lactobacillales,Lactobacillaceae,Leuconostoc,Leuconostoc gasicomitatum,MTIYDTEQIKSFLGLRQIKSNDDFKAVETMSTDTAIKFKKYVEYLG...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380018,380018,GCF_012029695_NZ_CP061389_Zorya_TypeI_1,GCF_012029695.2,NZ_CP061389,Zorya,Zorya_TypeI,GCF_012029695.2_NZ_CP061389_04302,GCF_012029695.2_NZ_CP061389_04305,GCF_012029695_NZ_CP061389_04305,4.0,Zorya__ZorA,WP_004178700.1,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Klebsiella,Klebsiella pneumoniae,MSWLNSFLVTLTSVEPHNVPFTVISIVSLAVACFLFFYLFRAIKIV...
380019,380019,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1,NZ_AP018052,Zorya,Zorya_TypeI,GCF_002356355.1_NZ_AP018052_01338,GCF_002356355.1_NZ_AP018052_01341,GCF_002356355_NZ_AP018052_01338,4.0,Zorya__ZorA2,WP_096365918.1,Bacteria,Pseudomonadota,Gammaproteobacteria,Chromatiales,NaN,Thiohalobacter,Thiohalobacter thiocyanaticus,MSTKHLAELLDRLANAIVTLEGVALICILIALVALYNYLRFRARIA...
380020,380020,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1,NZ_AP018052,Zorya,Zorya_TypeI,GCF_002356355.1_NZ_AP018052_01338,GCF_002356355.1_NZ_AP018052_01341,GCF_002356355_NZ_AP018052_01339,4.0,Zorya__ZorB,WP_197703019.1,Bacteria,Pseudomonadota,Gammaproteobacteria,Chromatiales,NaN,Thiohalobacter,Thiohalobacter thiocyanaticus,MKRPAEHTTFEDDGAGYLISVSDMMAGLLFVFMITLMAFVINFQQA...
380021,380021,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1,NZ_AP018052,Zorya,Zorya_TypeI,GCF_002356355.1_NZ_AP018052_01338,GCF_002356355.1_NZ_AP018052_01341,GCF_002356355_NZ_AP018052_01340,4.0,Zorya_TypeI__ZorC,WP_157745444.1,Bacteria,Pseudomonadota,Gammaproteobacteria,Chromatiales,NaN,Thiohalobacter,Thiohalobacter thiocyanaticus,MAGLKESLSSRVVTSPHSESWPAPALETAIREARWKLARVEPRDPP...
380022,380022,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1,NZ_AP018052,Zorya,Zorya_TypeI,GCF_002356355.1_NZ_AP018052_01338,GCF_002356355.1_NZ_AP018052_01341,GCF_002356355_NZ_AP018052_01341,4.0,Zorya_TypeI__ZorD,WP_096365920.1,Bacteria,Pseudomonadota,Gammaproteobacteria,Chromatiales,NaN,Thiohalobacter,Thiohalobacter thiocyanaticus,MAELAWHVKDDGVEFQLQAEGKRVPLDQWGMHSIDLSSGQGTPGPL...

In [9]:
clusters

,rep_idx,member_idx
0,0|GCF_023612275_NZ_CP063766_Abi2_1,0|GCF_023612275_NZ_CP063766_Abi2_1
1,0|GCF_023612275_NZ_CP063766_Abi2_1,24|GCF_001587115_NZ_CP011828_Abi2_1
2,0|GCF_023612275_NZ_CP063766_Abi2_1,32|GCF_015377765_NZ_CP045602_Abi2_1
3,0|GCF_023612275_NZ_CP063766_Abi2_1,243|GCF_002216705_NZ_CP022340_Abi2_1
4,0|GCF_023612275_NZ_CP063766_Abi2_1,321|GCF_003667965_NZ_CP033041_Abi2_1
...,...,...
380018,279114|GCF_009662315_NZ_CP045739_RM_Type_IV_5,279285|GCF_900243355_NZ_LT969520_RM_Type_IV_2
380019,279114|GCF_009662315_NZ_CP045739_RM_Type_IV_5,280784|GCF_023093935_NZ_CP095770_RM_Type_IV_5
380020,279124|GCF_008824185_NZ_CP044424_RM_Type_I_1,279124|GCF_008824185_NZ_CP044424_RM_Type_I_1
380021,279124|GCF_008824185_NZ_CP044424_RM_Type_I_1,256701|GCF_023374775_NZ_CP090751_RM_Type_I_1
380022,279125|GCF_008824185_NZ_CP044424_RM_Type_I_1,279125|GCF_008824185_NZ_CP044424_RM_Type_I_1

In [69]:
df_expanded["cluster_rep"] = df_expanded.index.map(
    clusters.set_index("member_idx")["rep_idx"]
)

In [11]:
df_reps = df_expanded[df_expanded.index == df_expanded["cluster_rep"]]

In [72]:
from pathlib import Path

input_fasta = "./clustered_85/clusters_rep_seq.fasta"
num_batches = 8
output_prefix = "proteins_for_deeptmhmm_batch"

# Read FASTA records
records = []
with open(input_fasta) as f:
    record = []
    for line in f:
        if line.startswith(">") and record:
            records.append("".join(record))
            record = [line]
        else:
            record.append(line)
    if record:
        records.append("".join(record))

# Split records into batches
batch_size = (len(records) + num_batches - 1) // num_batches

for i in range(num_batches):
    batch_records = records[i * batch_size:(i + 1) * batch_size]
    if not batch_records:
        break

    out_file = f"{output_prefix}_{i+1}.fasta"
    with open(out_file, "w") as f:
        f.writelines(batch_records)

    print(f"Wrote {len(batch_records)} records to {out_file}")

Wrote 15390 records to proteins_for_deeptmhmm_batch_1.fasta
Wrote 15390 records to proteins_for_deeptmhmm_batch_2.fasta
Wrote 15390 records to proteins_for_deeptmhmm_batch_3.fasta
Wrote 15390 records to proteins_for_deeptmhmm_batch_4.fasta
Wrote 15390 records to proteins_for_deeptmhmm_batch_5.fasta
Wrote 15390 records to proteins_for_deeptmhmm_batch_6.fasta
Wrote 15390 records to proteins_for_deeptmhmm_batch_7.fasta
Wrote 15383 records to proteins_for_deeptmhmm_batch_8.fasta

In [ ]:
with open("proteins_clustered_90.fasta", "w") as f:
    for idx, seq in zip(df_reps.index, df_reps["protein_sequence"]):
        f.write(f">{idx}\n{seq}\n")

In [10]:
import re
import pandas as pd
from pathlib import Path

gff_paths = ['../DeepTMHMM-Academic-License-v1.0/results_batch_1/TMRs.gff3',
             '../DeepTMHMM-Academic-License-v1.0/results_batch_2/TMRs.gff3',
             '../DeepTMHMM-Academic-License-v1.0/results_batch_3/TMRs.gff3',
             '../DeepTMHMM-Academic-License-v1.0/results_batch_4/TMRs.gff3',
             '../DeepTMHMM-Academic-License-v1.0/results_batch_5/TMRs.gff3',
             '../DeepTMHMM-Academic-License-v1.0/results_batch_6/TMRs.gff3',
             '../DeepTMHMM-Academic-License-v1.0/results_batch_7/TMRs.gff3',
             '../DeepTMHMM-Academic-License-v1.0/results_batch_8/TMRs.gff3',
            ]  # directory with all .gff3 files

records = []

tmr_re = re.compile(r"#\s+(?P<seqid>\S+)\s+Number of predicted TMRs:\s+(?P<n>\d+)")

for gff in gff_paths:
    with open(gff) as f:
        for line in f:
            m = tmr_re.match(line)
            if m:
                records.append({
                    "cluster_rep": m.group("seqid"),
                    "n_tmr": int(m.group("n"))
                })

deeptmhmm_df = pd.DataFrame(records)

In [12]:
deeptmhmm_df['n_tmr'].value_counts()

n_tmr
0     120045
2       1181
1        767
3        580
4        529
6          6
5          3
8          1
12         1
Name: count, dtype: int64

In [13]:
three_line_paths = [
    "../DeepTMHMM-Academic-License-v1.0/results_batch_1/predicted_topologies.3line",
    "../DeepTMHMM-Academic-License-v1.0/results_batch_2/predicted_topologies.3line",
    "../DeepTMHMM-Academic-License-v1.0/results_batch_3/predicted_topologies.3line",
    "../DeepTMHMM-Academic-License-v1.0/results_batch_4/predicted_topologies.3line",
    "../DeepTMHMM-Academic-License-v1.0/results_batch_5/predicted_topologies.3line",
    "../DeepTMHMM-Academic-License-v1.0/results_batch_6/predicted_topologies.3line",
    "../DeepTMHMM-Academic-License-v1.0/results_batch_7/predicted_topologies.3line",
    "../DeepTMHMM-Academic-License-v1.0/results_batch_8/predicted_topologies.3line",
]
from pathlib import Path

three_line_files = []

import re
import pandas as pd
from pathlib import Path

gff_paths = ['../DeepTMHMM-Academic-License-v1.0/results_batch_1/TMRs.gff3',
             '../DeepTMHMM-Academic-License-v1.0/results_batch_2/TMRs.gff3',
             '../DeepTMHMM-Academic-License-v1.0/results_batch_3/TMRs.gff3',
             '../DeepTMHMM-Academic-License-v1.0/results_batch_4/TMRs.gff3',
             '../DeepTMHMM-Academic-License-v1.0/results_batch_5/TMRs.gff3',
             '../DeepTMHMM-Academic-License-v1.0/results_batch_6/TMRs.gff3',
             '../DeepTMHMM-Academic-License-v1.0/results_batch_7/TMRs.gff3',
             '../DeepTMHMM-Academic-License-v1.0/results_batch_8/TMRs.gff3',
            ]  # directory with all .gff3 files

records = []

tmr_re = re.compile(r"#\s+(?P<seqid>\S+)\s+Number of predicted TMRs:\s+(?P<n>\d+)")

for gff in gff_paths:
    with open(gff) as f:
        for line in f:
            m = tmr_re.match(line)
            if m:
                records.append({
                    "cluster_rep": m.group("seqid"),
                    "n_tmr": int(m.group("n"))
                })

deeptmhmm_df = pd.DataFrame(records)


for p in three_line_paths:
    p = Path(p)
    if p.is_dir():
        three_line_files.extend(p.rglob("*.3line"))
    elif p.is_file() and p.suffix == ".3line":
        three_line_files.append(p)
import pandas as pd

records = []

for file in three_line_files:
    with open(file) as f:
        while True:
            header = f.readline().rstrip()
            if not header:
                break

            seq = f.readline().rstrip()
            topo = f.readline().rstrip()

            # >346261|GCF_... | GLOB
            header_core = header[1:].split("|", 1)
            idx = int(header_core[0])
            rest = header_core[1]

            protein_id = rest.split(" | ")[0]

            n_tmr = topo.count("M")

            records.append({
                "cluster_rep_idx": idx,
                "protein_id": protein_id,
                "protein_sequence": seq,
                "n_tmr": n_tmr,
                "is_membrane": n_tmr > 0,
                "source_file": str(file)   # optional, very useful for debugging
            })

deeptmhmm_df = pd.DataFrame(records)

# same sequence should never have conflicting predictions
assert deeptmhmm_df.groupby("protein_sequence")["n_tmr"].nunique().max() == 1

# reduce to unique predictions
deeptmhmm_df = deeptmhmm_df.drop_duplicates(
    subset=["cluster_rep_idx", "protein_sequence"]
)

In [39]:
clusters['member_idx'] = clusters['member_idx'].astype(int)

In [48]:
df_expanded

,Unnamed: 0,sys_id,Assembly,replicon,type,subtype,sys_beg,sys_end,protein_in_syst,genes_count,name_of_profiles_in_sys,accession_in_sys,Superkingdom,phylum,class,order,family,genus,species,protein_sequence
0,0,GCF_023612275_NZ_CP063766_Abi2_1,GCF_023612275.1,NZ_CP063766,Abi2,Abi2,GCF_023612275.1_NZ_CP063766_01013,GCF_023612275.1_NZ_CP063766_01013,GCF_023612275.1_NZ_CP063766_01013,1.0,Abi2__Abi_2,WP_010728290.1,Bacteria,Bacillota,Bacilli,Lactobacillales,Enterococcaceae,Enterococcus,Enterococcus lactis,MKKYGSKQEYVKRPKSIINNRFPSKLKKKIRPNQYFYSRVRCQIIP...
1,1,GCF_900660665_NZ_LR215037_Abi2_1,GCF_900660665.1,NZ_LR215037,Abi2,Abi2,GCF_900660665.1_NZ_LR215037_00128,GCF_900660665.1_NZ_LR215037_00128,GCF_900660665.1_NZ_LR215037_00128,1.0,Abi2__Abi_2,WP_129646131.1,Bacteria,Mycoplasmatota,Mollicutes,Mycoplasmatales,Mycoplasmataceae,Mycoplasmopsis,Mycoplasmopsis maculosa,MNKNNVKSLLSFEEQLNFLQSKYINWNNQEKFRFKIYLINYGYSHM...
2,2,GCF_900660665_NZ_LR215037_Abi2_2,GCF_900660665.1,NZ_LR215037,Abi2,Abi2,GCF_900660665.1_NZ_LR215037_00677,GCF_900660665.1_NZ_LR215037_00677,GCF_900660665.1_NZ_LR215037_00677,1.0,Abi2__Abi_2,WP_129647121.1,Bacteria,Mycoplasmatota,Mollicutes,Mycoplasmatales,Mycoplasmataceae,Mycoplasmopsis,Mycoplasmopsis maculosa,MNKKIKTILTTDEQINLLEEWGLKWEDDYSRNILKIYLKNYGYKHI...
3,3,GCF_008365255_NZ_CP043501_Abi2_1,GCF_008365255.1,NZ_CP043501,Abi2,Abi2,GCF_008365255.1_NZ_CP043501_01947,GCF_008365255.1_NZ_CP043501_01947,GCF_008365255.1_NZ_CP043501_01947,1.0,Abi2__Abi_2,WP_149208562.1,Bacteria,Bacillota,Bacilli,Bacillales,Bacillaceae,Bacillus,Bacillus paralicheniformis,MVKGKTTNGLMRHLREKHGISINGSKHKKELLNMGYYHGYKGYRFI...
4,4,GCF_009296125_NZ_CP017197_Abi2_1,GCF_009296125.1,NZ_CP017197,Abi2,Abi2,GCF_009296125.1_NZ_CP017197_01353,GCF_009296125.1_NZ_CP017197_01353,GCF_009296125.1_NZ_CP017197_01353,1.0,Abi2__Abi_2,WP_097001356.1,Bacteria,Bacillota,Bacilli,Lactobacillales,Lactobacillaceae,Leuconostoc,Leuconostoc gasicomitatum,MTIYDTEQIKSFLGLRQIKSNDDFKAVETMSTDTAIKFKKYVEYLG...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380018,380018,GCF_012029695_NZ_CP061389_Zorya_TypeI_1,GCF_012029695.2,NZ_CP061389,Zorya,Zorya_TypeI,GCF_012029695.2_NZ_CP061389_04302,GCF_012029695.2_NZ_CP061389_04305,GCF_012029695_NZ_CP061389_04305,4.0,Zorya__ZorA,WP_004178700.1,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Klebsiella,Klebsiella pneumoniae,MSWLNSFLVTLTSVEPHNVPFTVISIVSLAVACFLFFYLFRAIKIV...
380019,380019,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1,NZ_AP018052,Zorya,Zorya_TypeI,GCF_002356355.1_NZ_AP018052_01338,GCF_002356355.1_NZ_AP018052_01341,GCF_002356355_NZ_AP018052_01338,4.0,Zorya__ZorA2,WP_096365918.1,Bacteria,Pseudomonadota,Gammaproteobacteria,Chromatiales,NaN,Thiohalobacter,Thiohalobacter thiocyanaticus,MSTKHLAELLDRLANAIVTLEGVALICILIALVALYNYLRFRARIA...
380020,380020,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1,NZ_AP018052,Zorya,Zorya_TypeI,GCF_002356355.1_NZ_AP018052_01338,GCF_002356355.1_NZ_AP018052_01341,GCF_002356355_NZ_AP018052_01339,4.0,Zorya__ZorB,WP_197703019.1,Bacteria,Pseudomonadota,Gammaproteobacteria,Chromatiales,NaN,Thiohalobacter,Thiohalobacter thiocyanaticus,MKRPAEHTTFEDDGAGYLISVSDMMAGLLFVFMITLMAFVINFQQA...
380021,380021,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1,NZ_AP018052,Zorya,Zorya_TypeI,GCF_002356355.1_NZ_AP018052_01338,GCF_002356355.1_NZ_AP018052_01341,GCF_002356355_NZ_AP018052_01340,4.0,Zorya_TypeI__ZorC,WP_157745444.1,Bacteria,Pseudomonadota,Gammaproteobacteria,Chromatiales,NaN,Thiohalobacter,Thiohalobacter thiocyanaticus,MAGLKESLSSRVVTSPHSESWPAPALETAIREARWKLARVEPRDPP...
380022,380022,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1,NZ_AP018052,Zorya,Zorya_TypeI,GCF_002356355.1_NZ_AP018052_01338,GCF_002356355.1_NZ_AP018052_01341,GCF_002356355_NZ_AP018052_01341,4.0,Zorya_TypeI__ZorD,WP_096365920.1,Bacteria,Pseudomonadota,Gammaproteobacteria,Chromatiales,NaN,Thiohalobacter,Thiohalobacter thiocyanaticus,MAELAWHVKDDGVEFQLQAEGKRVPLDQWGMHSIDLSSGQGTPGPL...

In [53]:
df = clusters.merge(df_expanded,
                right_on='Unnamed: 0',
                left_on='member_idx',
                how='outer',
                validate='one_to_one')

In [ ]:
clusters = pd.read_csv(
    "./clustered_85/clusters_cluster.tsv",
    sep="\t",
    header=None,
    names=["cluster_rep", "member"]
)

# remove numeric prefix before '|'
clusters[["cluster_idx","cluster_rep",]] = clusters["cluster_rep"].str.split("|", n=1, expand=True)
clusters[["member_idx","member",]]  = clusters["member"].str.split("|", n=1, expand=True)

In [58]:
df['cluster_idx'] = df['cluster_idx'].astype(int)

In [60]:
deeptmhmm_df['cluster_rep_idx'] = deeptmhmm_df['cluster_rep_idx'].astype(int)

In [62]:
df = df.merge(deeptmhmm_df,
                right_on='cluster_rep_idx',
                left_on='cluster_idx',
                how='outer',
                validate='many_to_one')

In [65]:
df.columns

Index(['index', 'cluster_rep', 'member', 'cluster_idx', 'member_idx',
       'Unnamed: 0', 'sys_id', 'Assembly', 'replicon', 'type', 'subtype',
       'sys_beg', 'sys_end', 'protein_in_syst', 'genes_count',
       'name_of_profiles_in_sys', 'accession_in_sys', 'Superkingdom', 'phylum',
       'class', 'order', 'family', 'genus', 'species', 'protein_sequence_x',
       'cluster_rep_idx', 'protein_id', 'protein_sequence_y', 'n_tmr',
       'is_membrane', 'source_file'],
      dtype='object')

In [69]:
df

,index,cluster_rep,member,cluster_idx,member_idx,Unnamed: 0,sys_id,Assembly,replicon,type,...,family,genus,species,protein_sequence_x,cluster_rep_idx,protein_id,protein_sequence_y,n_tmr,is_membrane,source_file
0,0,GCF_023612275_NZ_CP063766_Abi2_1,GCF_023612275_NZ_CP063766_Abi2_1,0,0,0,GCF_023612275_NZ_CP063766_Abi2_1,GCF_023612275.1,NZ_CP063766,Abi2,...,Enterococcaceae,Enterococcus,Enterococcus lactis,MKKYGSKQEYVKRPKSIINNRFPSKLKKKIRPNQYFYSRVRCQIIP...,0,GCF_023612275_NZ_CP063766_Abi2_1,MKKYGSKQEYVKRPKSIINNRFPSKLKKKIRPNQYFYSRVRCQIIP...,0,False,../DeepTMHMM-Academic-License-v1.0/results_bat...
1,1,GCF_023612275_NZ_CP063766_Abi2_1,GCF_001587115_NZ_CP011828_Abi2_1,0,24,24,GCF_001587115_NZ_CP011828_Abi2_1,GCF_001587115.1,NZ_CP011828,Abi2,...,Enterococcaceae,Enterococcus,Enterococcus faecium,MKKYGSKQEYVKRPKSIINNRFPSKLKKKIRPNQYFYSRVRCQIIP...,0,GCF_023612275_NZ_CP063766_Abi2_1,MKKYGSKQEYVKRPKSIINNRFPSKLKKKIRPNQYFYSRVRCQIIP...,0,False,../DeepTMHMM-Academic-License-v1.0/results_bat...
2,2,GCF_023612275_NZ_CP063766_Abi2_1,GCF_015377765_NZ_CP045602_Abi2_1,0,32,32,GCF_015377765_NZ_CP045602_Abi2_1,GCF_015377765.1,NZ_CP045602,Abi2,...,Enterococcaceae,Enterococcus,Enterococcus faecium,MKKYGSKQEYVKRPKSIINNRFPSKLKKKIRPNQYFYSRVRCQIIP...,0,GCF_023612275_NZ_CP063766_Abi2_1,MKKYGSKQEYVKRPKSIINNRFPSKLKKKIRPNQYFYSRVRCQIIP...,0,False,../DeepTMHMM-Academic-License-v1.0/results_bat...
3,3,GCF_023612275_NZ_CP063766_Abi2_1,GCF_002216705_NZ_CP022340_Abi2_1,0,243,243,GCF_002216705_NZ_CP022340_Abi2_1,GCF_002216705.1,NZ_CP022340,Abi2,...,Enterococcaceae,Enterococcus,Enterococcus mundtii,MRKYGSKQEYVKRPKSIINNRFPSELKKKIRPNQYFYSRVRCQIIP...,0,GCF_023612275_NZ_CP063766_Abi2_1,MKKYGSKQEYVKRPKSIINNRFPSKLKKKIRPNQYFYSRVRCQIIP...,0,False,../DeepTMHMM-Academic-License-v1.0/results_bat...
4,4,GCF_023612275_NZ_CP063766_Abi2_1,GCF_003667965_NZ_CP033041_Abi2_1,0,321,321,GCF_003667965_NZ_CP033041_Abi2_1,GCF_003667965.1,NZ_CP033041,Abi2,...,Enterococcaceae,Enterococcus,Enterococcus faecium,MKKYGSKQEYVKRPKSIINNRFPSKLKKKIRPNQYFYSRVRCQIIP...,0,GCF_023612275_NZ_CP063766_Abi2_1,MKKYGSKQEYVKRPKSIINNRFPSKLKKKIRPNQYFYSRVRCQIIP...,0,False,../DeepTMHMM-Academic-License-v1.0/results_bat...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380018,297390,GCF_014396975_NZ_CP060719_Zorya_TypeI_1,GCF_014396975_NZ_CP060719_Zorya_TypeI_1,380010,380010,380010,GCF_014396975_NZ_CP060719_Zorya_TypeI_1,GCF_014396975.1,NZ_CP060719,Zorya,...,Xanthomonadaceae,Thermomonas,Thermomonas carbonis,MLGFWSHLTGTAFIAALSSISVLLIVHFLWQYVIRGVRLRRELKGL...,380010,GCF_014396975_NZ_CP060719_Zorya_TypeI_1,MLGFWSHLTGTAFIAALSSISVLLIVHFLWQYVIRGVRLRRELKGL...,63,True,../DeepTMHMM-Academic-License-v1.0/results_bat...
380019,297391,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,380019,380019,380019,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1,NZ_AP018052,Zorya,...,NaN,Thiohalobacter,Thiohalobacter thiocyanaticus,MSTKHLAELLDRLANAIVTLEGVALICILIALVALYNYLRFRARIA...,380019,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,MSTKHLAELLDRLANAIVTLEGVALICILIALVALYNYLRFRARIA...,60,True,../DeepTMHMM-Academic-License-v1.0/results_bat...
380020,297392,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,380020,380020,380020,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1,NZ_AP018052,Zorya,...,NaN,Thiohalobacter,Thiohalobacter thiocyanaticus,MKRPAEHTTFEDDGAGYLISVSDMMAGLLFVFMITLMAFVINFQQA...,380020,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,MKRPAEHTTFEDDGAGYLISVSDMMAGLLFVFMITLMAFVINFQQA...,18,True,../DeepTMHMM-Academic-License-v1.0/results_bat...
380021,297393,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,380021,380021,380021,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1,NZ_AP018052,Zorya,...,NaN,Thiohalobacter,Thiohalobacter thiocyanaticus,MAGLKESLSSRVVTSPHSESWPAPALETAIREARWKLARVEPRDPP...,380021,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,MAGLKESLSSRVVTSPHSESWPAPALETAIREARWKLARVEPRDPP...,0,False,../DeepTMHMM-Academic-License-v1.0/results_bat...
380022,297394,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,380022,380022,380022,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1,NZ_AP018052,Zorya,...,NaN,Thiohalobacter,Thiohalobacter thiocyanaticus,MAELAWHVKDDGVEFQLQAEGKRVPLDQWGMHSIDLSSGQGTPGPL...,380022,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,MAELAWHVKDDGVEFQLQAEGKRVPLDQWGMHSIDLSSGQGTPGPL...,0,False,../DeepTMHMM-Academic-License-v1.0/results_bat...

In [68]:
df_expanded

,Unnamed: 0,sys_id,Assembly,replicon,type,subtype,sys_beg,sys_end,protein_in_syst,genes_count,name_of_profiles_in_sys,accession_in_sys,Superkingdom,phylum,class,order,family,genus,species,protein_sequence
0,0,GCF_023612275_NZ_CP063766_Abi2_1,GCF_023612275.1,NZ_CP063766,Abi2,Abi2,GCF_023612275.1_NZ_CP063766_01013,GCF_023612275.1_NZ_CP063766_01013,GCF_023612275.1_NZ_CP063766_01013,1.0,Abi2__Abi_2,WP_010728290.1,Bacteria,Bacillota,Bacilli,Lactobacillales,Enterococcaceae,Enterococcus,Enterococcus lactis,MKKYGSKQEYVKRPKSIINNRFPSKLKKKIRPNQYFYSRVRCQIIP...
1,1,GCF_900660665_NZ_LR215037_Abi2_1,GCF_900660665.1,NZ_LR215037,Abi2,Abi2,GCF_900660665.1_NZ_LR215037_00128,GCF_900660665.1_NZ_LR215037_00128,GCF_900660665.1_NZ_LR215037_00128,1.0,Abi2__Abi_2,WP_129646131.1,Bacteria,Mycoplasmatota,Mollicutes,Mycoplasmatales,Mycoplasmataceae,Mycoplasmopsis,Mycoplasmopsis maculosa,MNKNNVKSLLSFEEQLNFLQSKYINWNNQEKFRFKIYLINYGYSHM...
2,2,GCF_900660665_NZ_LR215037_Abi2_2,GCF_900660665.1,NZ_LR215037,Abi2,Abi2,GCF_900660665.1_NZ_LR215037_00677,GCF_900660665.1_NZ_LR215037_00677,GCF_900660665.1_NZ_LR215037_00677,1.0,Abi2__Abi_2,WP_129647121.1,Bacteria,Mycoplasmatota,Mollicutes,Mycoplasmatales,Mycoplasmataceae,Mycoplasmopsis,Mycoplasmopsis maculosa,MNKKIKTILTTDEQINLLEEWGLKWEDDYSRNILKIYLKNYGYKHI...
3,3,GCF_008365255_NZ_CP043501_Abi2_1,GCF_008365255.1,NZ_CP043501,Abi2,Abi2,GCF_008365255.1_NZ_CP043501_01947,GCF_008365255.1_NZ_CP043501_01947,GCF_008365255.1_NZ_CP043501_01947,1.0,Abi2__Abi_2,WP_149208562.1,Bacteria,Bacillota,Bacilli,Bacillales,Bacillaceae,Bacillus,Bacillus paralicheniformis,MVKGKTTNGLMRHLREKHGISINGSKHKKELLNMGYYHGYKGYRFI...
4,4,GCF_009296125_NZ_CP017197_Abi2_1,GCF_009296125.1,NZ_CP017197,Abi2,Abi2,GCF_009296125.1_NZ_CP017197_01353,GCF_009296125.1_NZ_CP017197_01353,GCF_009296125.1_NZ_CP017197_01353,1.0,Abi2__Abi_2,WP_097001356.1,Bacteria,Bacillota,Bacilli,Lactobacillales,Lactobacillaceae,Leuconostoc,Leuconostoc gasicomitatum,MTIYDTEQIKSFLGLRQIKSNDDFKAVETMSTDTAIKFKKYVEYLG...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380018,380018,GCF_012029695_NZ_CP061389_Zorya_TypeI_1,GCF_012029695.2,NZ_CP061389,Zorya,Zorya_TypeI,GCF_012029695.2_NZ_CP061389_04302,GCF_012029695.2_NZ_CP061389_04305,GCF_012029695_NZ_CP061389_04305,4.0,Zorya__ZorA,WP_004178700.1,Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Klebsiella,Klebsiella pneumoniae,MSWLNSFLVTLTSVEPHNVPFTVISIVSLAVACFLFFYLFRAIKIV...
380019,380019,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1,NZ_AP018052,Zorya,Zorya_TypeI,GCF_002356355.1_NZ_AP018052_01338,GCF_002356355.1_NZ_AP018052_01341,GCF_002356355_NZ_AP018052_01338,4.0,Zorya__ZorA2,WP_096365918.1,Bacteria,Pseudomonadota,Gammaproteobacteria,Chromatiales,NaN,Thiohalobacter,Thiohalobacter thiocyanaticus,MSTKHLAELLDRLANAIVTLEGVALICILIALVALYNYLRFRARIA...
380020,380020,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1,NZ_AP018052,Zorya,Zorya_TypeI,GCF_002356355.1_NZ_AP018052_01338,GCF_002356355.1_NZ_AP018052_01341,GCF_002356355_NZ_AP018052_01339,4.0,Zorya__ZorB,WP_197703019.1,Bacteria,Pseudomonadota,Gammaproteobacteria,Chromatiales,NaN,Thiohalobacter,Thiohalobacter thiocyanaticus,MKRPAEHTTFEDDGAGYLISVSDMMAGLLFVFMITLMAFVINFQQA...
380021,380021,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1,NZ_AP018052,Zorya,Zorya_TypeI,GCF_002356355.1_NZ_AP018052_01338,GCF_002356355.1_NZ_AP018052_01341,GCF_002356355_NZ_AP018052_01340,4.0,Zorya_TypeI__ZorC,WP_157745444.1,Bacteria,Pseudomonadota,Gammaproteobacteria,Chromatiales,NaN,Thiohalobacter,Thiohalobacter thiocyanaticus,MAGLKESLSSRVVTSPHSESWPAPALETAIREARWKLARVEPRDPP...
380022,380022,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1,NZ_AP018052,Zorya,Zorya_TypeI,GCF_002356355.1_NZ_AP018052_01338,GCF_002356355.1_NZ_AP018052_01341,GCF_002356355_NZ_AP018052_01341,4.0,Zorya_TypeI__ZorD,WP_096365920.1,Bacteria,Pseudomonadota,Gammaproteobacteria,Chromatiales,NaN,Thiohalobacter,Thiohalobacter thiocyanaticus,MAELAWHVKDDGVEFQLQAEGKRVPLDQWGMHSIDLSSGQGTPGPL...

In [72]:
df_unexpanded = df.groupby(
    'sys_id', as_index=False).agg(
    number_of_membrane_proteins=(
        'is_membrane', 'sum'),is_membrane_associated=('is_membrane', 'any'))

In [73]:
df_unexpanded

,sys_id,number_of_membrane_proteins,is_membrane_associated
0,GCF_000005825_NC_013791_AbiH_1,0,False
1,GCF_000005825_NC_013791_AbiR_2,0,False
2,GCF_000005825_NC_013791_Gao_Her_DUF_1,0,False
3,GCF_000005825_NC_013791_Lamassu-PDDEXK_3,0,False
4,GCF_000005825_NC_013791_PD-Lambda-1_1,1,True
...,...,...,...
172328,GCF_940677205_NZ_OW712331_RM_Type_I_1,0,False
172329,GCF_940796315_NZ_OW724079_RM_Type_IIG_1,0,False
172330,GCF_942548115_NZ_OW824151_Gabija_1,0,False
172331,GCF_942548115_NZ_OW824151_RM_Type_II_2,0,False
172332,GCF_942548115_NZ_OW824151_RM_Type_I_1,0,False

In [74]:
df_refseq

,sys_id,Assembly,replicon,type,subtype,sys_beg,sys_end,protein_in_syst,genes_count,name_of_profiles_in_sys,accession_in_sys,Superkingdom,phylum,class,order,family,genus,species
0,GCF_023612275_NZ_CP063766_Abi2_1,GCF_023612275.1,NZ_CP063766,Abi2,Abi2,GCF_023612275.1_NZ_CP063766_01013,GCF_023612275.1_NZ_CP063766_01013,GCF_023612275.1_NZ_CP063766_01013,1.0,Abi2__Abi_2,WP_010728290.1,Bacteria,Bacillota,Bacilli,Lactobacillales,Enterococcaceae,Enterococcus,Enterococcus lactis
1,GCF_900660665_NZ_LR215037_Abi2_1,GCF_900660665.1,NZ_LR215037,Abi2,Abi2,GCF_900660665.1_NZ_LR215037_00128,GCF_900660665.1_NZ_LR215037_00128,GCF_900660665.1_NZ_LR215037_00128,1.0,Abi2__Abi_2,WP_129646131.1,Bacteria,Mycoplasmatota,Mollicutes,Mycoplasmatales,Mycoplasmataceae,Mycoplasmopsis,Mycoplasmopsis maculosa
2,GCF_900660665_NZ_LR215037_Abi2_2,GCF_900660665.1,NZ_LR215037,Abi2,Abi2,GCF_900660665.1_NZ_LR215037_00677,GCF_900660665.1_NZ_LR215037_00677,GCF_900660665.1_NZ_LR215037_00677,1.0,Abi2__Abi_2,WP_129647121.1,Bacteria,Mycoplasmatota,Mollicutes,Mycoplasmatales,Mycoplasmataceae,Mycoplasmopsis,Mycoplasmopsis maculosa
3,GCF_008365255_NZ_CP043501_Abi2_1,GCF_008365255.1,NZ_CP043501,Abi2,Abi2,GCF_008365255.1_NZ_CP043501_01947,GCF_008365255.1_NZ_CP043501_01947,GCF_008365255.1_NZ_CP043501_01947,1.0,Abi2__Abi_2,WP_149208562.1,Bacteria,Bacillota,Bacilli,Bacillales,Bacillaceae,Bacillus,Bacillus paralicheniformis
4,GCF_009296125_NZ_CP017197_Abi2_1,GCF_009296125.1,NZ_CP017197,Abi2,Abi2,GCF_009296125.1_NZ_CP017197_01353,GCF_009296125.1_NZ_CP017197_01353,GCF_009296125.1_NZ_CP017197_01353,1.0,Abi2__Abi_2,WP_097001356.1,Bacteria,Bacillota,Bacilli,Lactobacillales,Lactobacillaceae,Leuconostoc,Leuconostoc gasicomitatum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172328,GCF_012029695_NZ_CP061390_Zorya_TypeI_1,GCF_012029695.2,NZ_CP061390,Zorya,Zorya_TypeI,GCF_012029695.2_NZ_CP061390_00118,GCF_012029695.2_NZ_CP061390_00121,"GCF_012029695_NZ_CP061390_00118,GCF_012029695_...",4.0,"Zorya__ZorA,Zorya__ZorB,Zorya_TypeI__ZorC,Zory...","WP_004182103.1,WP_004182101.1,WP_004182099.1,W...",Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Klebsiella,Klebsiella pneumoniae
172329,GCF_014396975_NZ_CP060719_Zorya_TypeI_1,GCF_014396975.1,NZ_CP060719,Zorya,Zorya_TypeI,GCF_014396975.1_NZ_CP060719_00618,GCF_014396975.1_NZ_CP060719_00621,"GCF_014396975_NZ_CP060719_00618,GCF_014396975_...",4.0,"Zorya_TypeI__ZorD,Zorya_TypeI__ZorC,Zorya__Zor...","WP_187553130.1,WP_187553131.1,WP_187553132.1,W...",Bacteria,Pseudomonadota,Gammaproteobacteria,Xanthomonadales,Xanthomonadaceae,Thermomonas,Thermomonas carbonis
172330,GCF_002055855_NZ_CP020067_Zorya_TypeI_1,GCF_002055855.1,NZ_CP020067,Zorya,Zorya_TypeI,GCF_002055855.1_NZ_CP020067_01216,GCF_002055855.1_NZ_CP020067_01219,"GCF_002055855_NZ_CP020067_01216,GCF_002055855_...",4.0,"Zorya_TypeI__ZorD,Zorya_TypeI__ZorC,Zorya__Zor...","WP_004178705.1,WP_004178703.1,WP_004195968.1,W...",Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Klebsiella,Klebsiella pneumoniae
172331,GCF_012029695_NZ_CP061389_Zorya_TypeI_1,GCF_012029695.2,NZ_CP061389,Zorya,Zorya_TypeI,GCF_012029695.2_NZ_CP061389_04302,GCF_012029695.2_NZ_CP061389_04305,"GCF_012029695_NZ_CP061389_04302,GCF_012029695_...",4.0,"Zorya_TypeI__ZorD,Zorya_TypeI__ZorC,Zorya__Zor...","WP_004178705.1,WP_004178703.1,WP_004195968.1,W...",Bacteria,Pseudomonadota,Gammaproteobacteria,Enterobacterales,Enterobacteriaceae,Klebsiella,Klebsiella pneumoniae
172332,GCF_002356355_NZ_AP018052_Zorya_TypeI_2,GCF_002356355.1,NZ_AP018052,Zorya,Zorya_TypeI,GCF_002356355.1_NZ_AP018052_01338,GCF_002356355.1_NZ_AP018052_01341,"GCF_002356355_NZ_AP018052_01338,GCF_002356355_...",4.0,"Zorya__ZorA2,Zorya__ZorB,Zorya_TypeI__ZorC,Zor...","WP_096365918.1,WP_197703019.1,WP_157745444.1,W...",Bacteria,Pseudomonadota,Gammaproteobacteria,Chromatiales,NaN,Thiohalobacter,Thiohalobacter thiocyanaticus

In [76]:
defensefinder_tmhmm = df_refseq.merge(df_unexpanded,
                on='sys_id',
                how='inner',
                validate = 'one_to_one',
               )

In [77]:
defensefinder_tmhmm.to_csv('defensefinder_tmhmm_results.csv')